baseURL = "/"
title = "phansy silkie"

paginate = 5

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts"
    weight = 10

#  [[menu.main]]
#    identifier = "about"
#    name = "whats up?"
#    url = "/about"
#    weight = 20

#  [[menu.main]]
#    identifier = "migrated posts"
#    name = "wordpress exports"
#    url = "/migrated-posts"
#    weight = 15	