title = "phansy silkie"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "whats up?"
    url = "/about"
    weight = 20
