backend:
  name: git-gateway
  branch: main

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"

local_backend: true

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Blurb", name: "blurb", widget: "text" }
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: "string", required: false },
                  { label: "Text", name: "text", widget: "text", required: false },
                ],
            }
          - { label: "Picture", name: "picture", widget: "image", required: false } # Optional picture field

      - file: "content/about/index.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "text", required: false }

  - name: "migrated posts"
    label: "Migrated posts"
    folder: "content/migrated-posts"
    path: "{{slug}}/index"
    media_folder: "" # Save images in the migrated post's own folder instead of the static folder
    public_folder: ""
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "home"
    label: "Home"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "above text", name: "blurb", widget: "markdown", required: false }
          - { label: "Picture", name: "picture", widget: "image", required: false } # Optional picture field
          - {
              label: "Section",
              name: "section",
              widget: "object",
              fields:
                [
                  { label: "Heading", name: "heading", widget: "string", required: false },
                  { label: "Body", name: "body", widget: "markdown", required: false },
                ],
            }
